<?xml version="1.0" encoding="utf-8"?><Database Name="FinalProject" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-98LRLMSM;Initial Catalog=FinalProject;Integrated Security=True" SettingsObjectName="FinalProject.Properties.Settings" SettingsPropertyName="FinalProjectConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student" Id="ID1">
      <Column Name="ID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="f_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="l_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="birthdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Student_Course" Member="Courses" ThisKey="ID" OtherKey="student_ID" Type="Course" />
    </Type>
  </Table>
  <Table Name="dbo.Lesson" Member="Lessons">
    <Type Name="Lesson" Id="ID2">
      <Column Name="ID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lesson_Course" Member="Courses" ThisKey="ID" OtherKey="lesson_ID" Type="Course" />
    </Type>
  </Table>
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course" Id="ID3">
      <Column Name="student_ID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lesson_ID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lesson_Course" Member="Lesson" ThisKey="lesson_ID" OtherKey="ID" Type="Lesson" IsForeignKey="true" />
      <Association Name="Student_Course" Member="Student" ThisKey="student_ID" OtherKey="ID" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.CourseSearchLesseon" Method="CourseSearchLesseon">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="CourseSearchLesseonResult">
      <Column Name="student_ID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CourseSearchStudent" Method="CourseSearchStudent">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="CourseSearchStudentResult">
      <Column Name="lesson_ID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertLesson" Method="InsertLesson">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Credit" Parameter="credit" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertCourse" Method="InsertCourse">
    <Parameter Name="StudentID" Parameter="studentID" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="LessonID" Parameter="lessonID" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SearchStudent" Method="SearchStudent">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.InsertStudent" Method="InsertStudent">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="FName" Parameter="fName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LName" Parameter="lName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BirthDate" Parameter="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SearchLesson" Method="SearchLesson">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.SearchCourse" Method="SearchCourse">
    <Parameter Name="StudentID" Parameter="studentID" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="LessonID" Parameter="lessonID" Type="System.String" DbType="NVarChar(10)" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.UpdateStudent" Method="UpdateStudent">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="FName" Parameter="fName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LName" Parameter="lName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BirthDate" Parameter="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateLesson" Method="UpdateLesson">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Credit" Parameter="credit" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateCourse" Method="UpdateCourse">
    <Parameter Name="StudentID" Parameter="studentID" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="LessonName" Parameter="lessonName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Grade" Parameter="grade" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteStudent" Method="DeleteStudent">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteLesson" Method="DeleteLesson">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteCourse" Method="DeleteCourse">
    <Parameter Name="StudentID" Parameter="studentID" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="LessonID" Parameter="lessonID" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetStudentTable" Method="GetStudentTable">
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.GetLessonTable" Method="GetLessonTable">
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.GetCourseTable" Method="GetCourseTable">
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.StudentLessonsReport" Method="StudentLessonsReport">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.LessonStudentsReport" Method="LessonStudentsReport">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.GetAvg" Method="GetAvg">
    <ElementType Name="GetAvgResult1">
      <Column Name="average" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="student_ID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCountRejectedStudent" Method="GetCountRejectedStudent">
    <ElementType Name="GetCountRejectedStudentResult">
      <Column Name="lesson_ID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="rejectedCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>